# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Test create a database on container on raspberry
development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["PG_DATABASE"] %>
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  port: <%= ENV["PG_PORT_RASPBERRY"] %>
  host: <%= ENV["PG_RASPBERRY_HOST"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["PG_DATABASE"] %>_test
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  port: <%= ENV["PG_PORT_RASPBERRY"] %>
  host: <%= ENV["PG_RASPBERRY_HOST"] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["PG_DATABASE"] %>_production
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  port: <%= ENV["PG_PORT_RASPBERRY"] %>
  host: <%= ENV["PG_RASPBERRY_HOST"] %>